import type { VlmAnalysisResult } from "./vlm-prompt";

/**
 * Build a prompt for LLM to generate a DESIGN.md document
 * from VLM visual analysis results.
 */
export function buildDesignMdPrompt(
  vlmResult: VlmAnalysisResult,
  sourceDescription: string
): string {
  const colorSection = vlmResult.colorPalette
    ? `## Цветовая палитра

${vlmResult.colorPalette.dominantColors?.map(c => `- **${c.hex}** (${c.name}) — ${c.usage} — ~${c.percentage}%`).join("\n") || "Не определена"}

**CSS Variables:**\n${generateCssVariables(vlmResult.colorPalette)}`
    : "";

  const typoSection = vlmResult.typography
    ? `## Типографика

### Заголовки
- Стиль: ${vlmResult.typography.headings?.style || "N/A"}
- Вес: ${vlmResult.typography.headings?.weight || "N/A"}
- ${vlmResult.typography.headings?.characteristics || ""}

### Основной текст
- Стиль: ${vlmResult.typography.body?.style || "N/A"}
- Вес: ${vlmResult.typography.body?.weight || "N/A"}
- ${vlmResult.typography.body?.characteristics || ""}`
    : "";

  const layoutSection = vlmResult.layout
    ? `## Layout\n\n- Сетка: ${vlmResult.layout.gridType || "N/A"}\n- Density: ${vlmResult.layout.density || "N/A"}\n- Alignment: ${vlmResult.layout.alignment || "N/A"}\n- Max content width: ${vlmResult.layout.maxContentWidth || "N/A"}\n- Spacing: ${vlmResult.layout.spacing || "N/A"}`
    : "";

  const componentsSection = vlmResult.components?.length
    ? `## Компоненты\n\n${vlmResult.components.map(c => `### ${c.type}\n- Характеристики: ${c.characteristics}\n- Состояния: ${c.states.join(", ")}\n- Border radius: ${c.borderRadius}\n- Тени: ${c.shadows}`).join("\n\n")}`
    : "";

  const effectsSection = vlmResult.visualEffects?.length
    ? `## Визуальные эффекты\n\n${vlmResult.visualEffects.map(e => `- **${e.type}**: ${e.description}`).join("\n")}`
    : "";

  const moodSection = vlmResult.moodAndTone
    ? `## Настроение и тон\n\n- Ключевые слова: ${vlmResult.moodAndTone.keywords?.join(", ") || "N/A"}\n- ${vlmResult.moodAndTone.description || ""}`
    : "";

  const a11ySection = vlmResult.accessibilityNotes?.length
    ? `## Доступность\n\n${vlmResult.accessibilityNotes.map(n => `- ${n}`).join("\n")}`
    : "";

  const patternsSection = vlmResult.uiPatterns?.length
    ? `## UI-паттерны\n\n${vlmResult.uiPatterns.map(p => `- **${p.pattern}**: ${p.description}`).join("\n")}`
    : "";

  return `Ты — senior design-system engineer. На основе визуального анализа интерфейса составь формальный документ DESIGN.md.

Исходный материал — JSON-результат VLM-анализа и описание источника.

Формат документа — Markdown. Структура:

# Design System: ${sourceDescription}

> Автоматически сгенерировано на основе визуального анализа

## Обзор\n
2-3 предложения с общим описанием визуальной системы.

${colorSection}

${generateTailwindConfig(vlmResult.colorPalette)}

${typoSection}

${layoutSection}

${componentsSection}

${effectsSection}

${moodSection}

${a11ySection}

${patternsSection}

---

## Рекомендации по реализации

5-7 конкретных практических рекомендаций для разработчика, который будет воспроизводить этот дизайн.

---

Generated by UX Analyzer — VLM + LLM pipeline`;
}

function generateCssVariables(cp: NonNullable<VlmAnalysisResult["colorPalette"]>): string {
  const lines: string[] = ["```css", ":root {"];
  let i = 0;
  const addVar = (name: string, hex?: string) => {
    if (hex) {
      lines.push(`  --color-${name}: ${hex};`);
      i++;
    }
  };
  addVar("primary", cp.primary?.[0]);
  addVar("primary-foreground", cp.primary?.[1]);
  addVar("secondary", cp.secondary?.[0]);
  addVar("secondary-foreground", cp.secondary?.[1]);
  addVar("accent", cp.accent?.[0]);
  addVar("background", cp.background?.[0]);
  addVar("text", cp.text?.[0]);
  addVar("text-muted", cp.text?.[1]);
  lines.push("}");
  lines.push("```");
  return lines.join("\n");
}

function generateTailwindConfig(cp: NonNullable<VlmAnalysisResult["colorPalette"]> | undefined): string {
  if (!cp) return "";
  const colors: Record<string, string> = {};
  if (cp.primary?.[0]) colors["primary"] = cp.primary[0];
  if (cp.secondary?.[0]) colors["secondary"] = cp.secondary[0];
  if (cp.accent?.[0]) colors["accent"] = cp.accent[0];
  if (cp.background?.[0]) colors["background"] = cp.background[0];
  if (cp.text?.[0]) colors["foreground"] = cp.text[0];

  const colorEntries = Object.entries(colors)
    .map(([key, value]) => `      "${key}": "${value}"`)
    .join(",\n");

  return `**Tailwind Config:**
\n\`\`\`js
// tailwind.config.js — theme.extend.colors
module.exports = {
  theme: {
    extend: {
      colors: {
${colorEntries}
      }
    }
  }
};
\`\`\``;
}
