/**
 * Format reference code data into readable markdown.
 * Pure function — no side effects, exported for unit testing.
 */

export function formatReferenceCode(data: Record<string, unknown>, source: string): string {
  const lines: string[] = [];

  lines.push(`# Reference Implementation Pipeline: ${source}`);
  lines.push('');
  lines.push(`> Автоматически сгенерировано UX-Analyzer`);
  lines.push('');

  // Estimated complexity & time
  if (data.estimatedComplexity) {
    lines.push(
      `**Сложность:** ${data.estimatedComplexity} | **Время:** ${data.estimatedTime || 'N/A'}`,
    );
    lines.push('');
  }

  // Dependencies
  if (data.dependencies && typeof data.dependencies === 'object') {
    const deps = data.dependencies as Record<string, unknown>;
    lines.push('## Зависимости');
    lines.push('');
    if (deps.packages && Array.isArray(deps.packages)) {
      lines.push('```bash');
      lines.push(`bun add ${deps.packages.join(' ')}`);
      lines.push('```');
    }
    lines.push('');
  }

  // Design tokens
  if (data.designTokens && typeof data.designTokens === 'object') {
    const tokens = data.designTokens as Record<string, unknown>;
    lines.push('## Design Tokens');
    lines.push('');
    if (tokens.cssVariables) {
      lines.push('### CSS Variables');
      lines.push('');
      lines.push('```css');
      lines.push(String(tokens.cssVariables));
      lines.push('```');
      lines.push('');
    }
    if (tokens.tailwindConfig) {
      lines.push('### Tailwind Config');
      lines.push('');
      lines.push('```js');
      lines.push(String(tokens.tailwindConfig));
      lines.push('```');
      lines.push('');
    }
  }

  // File structure
  if (data.fileStructure && typeof data.fileStructure === 'object') {
    const fs = data.fileStructure as Record<string, unknown>;
    lines.push('## Файловая структура');
    lines.push('');
    lines.push('```');
    lines.push(String(fs.tree || fs.description || 'N/A'));
    lines.push('```');
    lines.push('');
  }

  // Phases
  if (data.phases && Array.isArray(data.phases)) {
    const phases = data.phases as Array<Record<string, unknown>>;
    lines.push('## Фазы реализации');
    lines.push('');

    for (const phase of phases) {
      lines.push(`### Фаза ${phase.phase}: ${phase.name}`);
      lines.push('');
      lines.push(String(phase.description));
      lines.push('');

      if (Array.isArray(phase.steps)) {
        const steps = phase.steps as Array<Record<string, unknown>>;
        for (const step of steps) {
          lines.push(`#### Шаг ${step.order}: ${step.title}`);
          lines.push('');
          lines.push(String(step.description));
          lines.push('');

          if (step.files && Array.isArray(step.files)) {
            lines.push(`**Файлы:** ${(step.files as string[]).join(', ')}`);
            lines.push('');
          }

          if (step.code) {
            lines.push('```tsx');
            lines.push(String(step.code));
            lines.push('```');
            lines.push('');
          }

          if (step.notes) {
            lines.push(`> ${String(step.notes)}`);
            lines.push('');
          }
        }
      }
    }
  }

  lines.push('---');
  lines.push('Generated by UX-Analyzer — Pipeline Architecture');

  return lines.join('\n');
}
