import { describe, it, expect } from "vitest";
import { formatReferenceCode } from "@/lib/pipeline/steps/reference-code";
import { buildReferenceCodePrompt } from "@/lib/reference-code-prompt";

describe("formatReferenceCode", () => {
  it("renders header and source description", () => {
    const result = formatReferenceCode({}, "Test Source");
    expect(result).toContain("# Reference Implementation Pipeline: Test Source");
    expect(result).toContain("UX-Analyzer");
  });

  it("renders estimated complexity and time", () => {
    const data = { estimatedComplexity: "medium", estimatedTime: "3-5 часов" };
    const result = formatReferenceCode(data, "test");
    expect(result).toContain("**Сложность:** medium");
    expect(result).toContain("**Время:** 3-5 часов");
  });

  it("renders dependencies with packages", () => {
    const data = {
      dependencies: {
        description: "Core deps",
        packages: ["next@15", "react@19", "tailwindcss@3"],
      },
    };
    const result = formatReferenceCode(data, "test");
    expect(result).toContain("## Зависимости");
    expect(result).toContain("bun add");
    expect(result).toContain("next@15");
    expect(result).toContain("react@19");
  });

  it("renders design tokens (CSS variables and Tailwind config)", () => {
    const data = {
      designTokens: {
        cssVariables: ":root { --primary: #10b981; --bg: #000; }",
        tailwindConfig: 'module.exports = { theme: { extend: { colors: { primary: "#10b981" } } } }',
      },
    };
    const result = formatReferenceCode(data, "test");
    expect(result).toContain("## Design Tokens");
    expect(result).toContain("### CSS Variables");
    expect(result).toContain("--primary: #10b981");
    expect(result).toContain("### Tailwind Config");
    expect(result).toContain("primary");
  });

  it("renders file structure", () => {
    const data = {
      fileStructure: {
        description: "Project structure",
        tree: "src/\n├── app/\n│   ├── page.tsx\n│   └── layout.tsx\n├── components/",
      },
    };
    const result = formatReferenceCode(data, "test");
    expect(result).toContain("## Файловая структура");
    expect(result).toContain("page.tsx");
    expect(result).toContain("components/");
  });

  it("renders phases with steps containing code", () => {
    const data = {
      phases: [
        {
          phase: 1,
          name: "Setup",
          description: "Initial project setup",
          steps: [
            {
              order: 1,
              title: "Create project",
              description: "Initialize Next.js project",
              files: ["package.json", "tsconfig.json"],
              code: 'const nextConfig = { reactStrictMode: true };\nexport default nextConfig;',
              notes: "Use TypeScript",
            },
            {
              order: 2,
              title: "Install deps",
              description: "Install dependencies",
              files: ["package.json"],
              notes: "No code for this step",
            },
          ],
        },
        {
          phase: 2,
          name: "Layout",
          description: "Build the layout",
          steps: [
            {
              order: 1,
              title: "Root layout",
              description: "Create app/layout.tsx",
              files: ["app/layout.tsx"],
              code: 'export default function RootLayout({ children }) {\n  return <html><body>{children}</body></html>;\n}',
            },
          ],
        },
      ],
    };
    const result = formatReferenceCode(data, "test");
    expect(result).toContain("## Фазы реализации");
    expect(result).toContain("### Фаза 1: Setup");
    expect(result).toContain("#### Шаг 1: Create project");
    expect(result).toContain("**Файлы:** package.json, tsconfig.json");
    expect(result).toContain("reactStrictMode");
    expect(result).toContain("> Use TypeScript");
    expect(result).toContain("### Фаза 2: Layout");
    expect(result).toContain("RootLayout");
  });

  it("handles empty data gracefully", () => {
    const result = formatReferenceCode({}, "test");
    expect(result).toContain("# Reference Implementation Pipeline: test");
    expect(result).toContain("UX-Analyzer");
    // No sections should appear for empty data
    expect(result).not.toContain("## Зависимости");
    expect(result).not.toContain("## Design Tokens");
    expect(result).not.toContain("## Файловая структура");
    expect(result).not.toContain("## Фазы реализации");
  });

  it("handles phases without steps", () => {
    const data = {
      phases: [{ phase: 1, name: "Setup", description: "Setup phase" }],
    };
    const result = formatReferenceCode(data, "test");
    expect(result).toContain("### Фаза 1: Setup");
    expect(result).toContain("Setup phase");
  });

  it("includes Generated by footer", () => {
    const result = formatReferenceCode({}, "test");
    expect(result).toContain("Generated by UX-Analyzer");
  });

  // ── Integration test with Pointer AI fixture ──
  it("formats Pointer AI analysis result as pipeline", () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fixture = require("../fixtures/pointer-ai-analysis-result.json");
    const { analysisResult, sourceDescription } = fixture;

    // Simulate what LLM would produce as reference data
    const mockReferenceData = {
      estimatedComplexity: "medium",
      estimatedTime: "5-7 часов",
      dependencies: {
        packages: ["next@15", "react@19", "tailwindcss@3", "framer-motion@11", "lucide-react@0.400"],
      },
      designTokens: {
        cssVariables: ":root { --primary: #6366f1; --primary-light: #818cf8; --background: #000000; --foreground: #fafafa; }",
        tailwindConfig: 'module.exports = { darkMode: ["class"], theme: { extend: { colors: { primary: "#6366f1" } } } }',
      },
      fileStructure: {
        tree: "pointer-landing/\n├── app/\n│   ├── globals.css\n│   ├── layout.tsx\n│   └── page.tsx\n├── components/",
      },
      phases: [
        {
          phase: 1,
          name: "Setup",
          description: "Initialize Next.js 15 project with Tailwind CSS v3",
          steps: [
            {
              order: 1,
              title: "Project initialization",
              description: "Create Next.js app with TypeScript",
              files: ["package.json", "tsconfig.json", "next.config.ts"],
              code: "npx create-next-app@latest pointer-landing --typescript --tailwind --eslint",
              notes: "Use App Router",
            },
          ],
        },
        {
          phase: 3,
          name: "Core Components",
          description: "Build Hero, Features, Pricing sections",
          steps: [
            {
              order: 5,
              title: "Hero Section with SVG background",
              description: "Centered hero with grid pattern and gradient blobs",
              files: ["components/hero-section.tsx"],
              code: 'export function HeroSection() {\n  return (\n    <section className="relative min-h-[600px] flex items-center justify-center">\n      <h1 className="text-5xl font-bold tracking-tight">Unleash AI</h1>\n    </section>\n  );\n}',
            },
          ],
        },
      ],
    };

    const result = formatReferenceCode(mockReferenceData, sourceDescription);
    expect(result).toContain("Pointer AI");
    expect(result).toContain("medium");
    expect(result).toContain("next@15");
    expect(result).toContain("--primary: #6366f1");
    expect(result).toContain("Hero Section");
    expect(result).toContain("Unleash AI");
  });
});

describe("buildReferenceCodePrompt", () => {
  it("includes analysis sections when data is present", () => {
    const analysisResult = {
      teardown: { title: "Test", visualStyle: "dark mode" },
      reverseEngineering: { frontend: { stack: "Next.js", confidence: "high" } },
      audit: { problems: [] },
    };
    const prompt = buildReferenceCodePrompt(analysisResult, null, null, "Test URL");
    expect(prompt).toContain("## Исходный анализ");
    expect(prompt).toContain("### Teardown");
    expect(prompt).toContain("dark mode");
    expect(prompt).toContain("### Reverse Engineering");
    expect(prompt).toContain("Next.js");
    expect(prompt).toContain("Test URL");
  });

  it("shows 'Нет данных' for missing sections", () => {
    const prompt = buildReferenceCodePrompt({}, null, null, "test");
    expect(prompt).toContain("Нет данных");
  });

  it("includes VLM data when provided", () => {
    const vlmResult = {
      colorPalette: { dominantColors: [{ hex: "#000", name: "Black", usage: "background", percentage: 60 }] },
      typography: { headings: { style: "Geist Sans", weight: "Bold" } },
      layout: { gridType: "CSS Grid", spacing: "Tailwind utilities" },
      components: [],
      visualEffects: [],
      moodAndTone: { keywords: ["dark", "professional"], description: "Dark SaaS aesthetic" },
    };
    const prompt = buildReferenceCodePrompt({}, vlmResult as any, null, "test");
    expect(prompt).toContain("### VLM Visual Analysis");
    expect(prompt).toContain("Geist Sans");
    expect(prompt).toContain("Black");
  });

  it("includes DESIGN.md excerpt when provided", () => {
    const designMd = "# Design System\n\n## Colors\nPrimary: #6366f1\n## Typography\nFont: Geist Sans\n".repeat(100);
    const prompt = buildReferenceCodePrompt({}, null, designMd, "test");
    expect(prompt).toContain("### Design System Document");
    expect(prompt).toContain("Primary: #6366f1");
  });

  it("truncates DESIGN.md to 3000 chars", () => {
    const longDesignMd = "# Design\n".repeat(1000); // ~12000 chars
    const prompt = buildReferenceCodePrompt({}, null, longDesignMd, "test");
    // Extract only the DESIGN.md excerpt (between its header and the next section)
    const afterDesignMd = prompt.split("### Design System Document")[1];
    const designMdExcerpt = afterDesignMd.split("\n---\n")[0];
    // The excerpt should be truncated to ~3000 chars
    expect(designMdExcerpt.length).toBeLessThan(3500);
  });

  it("includes output format JSON schema", () => {
    const prompt = buildReferenceCodePrompt({}, null, null, "test");
    expect(prompt).toContain("## Формат вывода");
    expect(prompt).toContain('"phases"');
    expect(prompt).toContain('"designTokens"');
    expect(prompt).toContain('"fileStructure"');
  });

  it("includes rules for code generation", () => {
    const prompt = buildReferenceCodePrompt({}, null, null, "test");
    expect(prompt).toContain("## Правила");
    expect(prompt).toContain("Tailwind CSS");
    expect(prompt).toContain("shadcn/ui");
    expect(prompt).toContain("РЕАЛЬНЫМ");
  });

  it("includes few-shot examples from Pointer AI", () => {
    const prompt = buildReferenceCodePrompt({}, null, null, "test");
    expect(prompt).toContain("Few-shot");
    expect(prompt).toContain("Pointer AI");
    expect(prompt).toContain("Design Tokens через Tailwind Config");
    expect(prompt).toContain("PricingSection");
    expect(prompt).toContain("BentoSection");
    expect(prompt).toContain("satisfies Config");
    expect(prompt).toContain('"use client"');
  });
});
